version: '3.8'

services:
  optimism-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:latest
    container_name: optimism-geth
    restart: unless-stopped
    ports:
      - "8550:8545"
      - "8551:8546"
      - "30323:30303"
    volumes:
      - /data/blockchain/storage/optimism:/data
    command:
      - --datadir=/data
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,net,web3,txpool,debug
      - --http.vhosts=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.api=eth,net,web3
      - --syncmode=snap
      - --op-network=op-mainnet
    networks:
      - blockchain

networks:
  blockchain:
    external: true
